---
- name: clone CSP Reporter | git
  git:
    repo: "https://github.com/stevenharradine/csp-reporter"
    dest: "{{ cspreporter_path }}"
    update: yes
    force: yes

- name: install | npm
  npm:
    path: "{{ cspreporter_path }}"

- name: start CSP Reporter on reboot | cron
  cron:
    name: "start travis dashboard server"
    user: "{{ cspreporter_user }}"
    special_time: reboot
    job: "cd {{ cspreporter_path }} && node server.js"
